import Head from 'next/head'
import Image from 'next/image'
import {getSession, signIn,signOut,useSession} from 'next-auth/react'
import { NextPage, NextPageContext } from 'next'
import { Box } from '@chakra-ui/react'
import Chat from '../components/Chat/Chat'
import Auth from '../components/Auth/Auth'
import { Session } from 'next-auth'
const Home:NextPage=()=> {
   const { data: session }=useSession();


   const reloadSession  =()=> {
    const event = new Event("visibilitychange");
    document.dispatchEvent(event);
   };
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box >
          {session?.user?.username ? <Chat session={session}/> : <Auth session={session} reloadSession={reloadSession}  />}
        </Box>
      </main>
    </div>
  )
  
}



export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);

  return{
    props:{
      session,
    }
  }

}


export default Home;

